<#
.SYNOPSIS
    Executes the generated T-SQL restore script against the local SQL Server instance.

.DESCRIPTION
    Reads the tscript.sql file generated by CreateRefreshScript.ps1 and executes it
    using Invoke-Sqlcmd. Provides structured logging, input validation, and error
    handling. Designed to run as Phase 4 of the AG refresh orchestration pipeline.

    Connects using Windows Authentication (the Hybrid Worker service account) — no
    SQL credentials required. The service account must have sysadmin or sufficient
    restore permissions on the instance.

.PARAMETER RestoreSqlScript
    Full path to the T-SQL restore script file (tscript.sql).
    Default: H:\WORKDIR\AutomatedRefresh\tscript.sql

.PARAMETER LogDirectory
    Directory where log files are written.
    Default: H:\WORKDIR\Logs

.PARAMETER SqlInstance
    SQL Server instance name. Defaults to localhost (.) for execution on the primary replica.
    Default: .

.NOTES
    Author       : Your Name | Co-Author
    Version      : 2.1
    Last Updated : April 2026
    Run Context  : Azure Automation Hybrid Runbook Worker
    Auth         : Windows Authentication via Hybrid Worker service account
#>

param (
    [string]$RestoreSqlScript = 'H:\WORKDIR\AutomatedRefresh\tscript.sql',
    [string]$LogDirectory     = 'H:\WORKDIR\Logs',
    [string]$SqlInstance      = '.'
)

#region Initialization

$ErrorActionPreference = 'Stop'
$VerbosePreference     = 'SilentlyContinue'

$TimeStamp   = Get-Date -Format 'yyyy-MM-dd'
$RunId       = [Guid]::NewGuid().ToString().Substring(0, 8)
$LogFilePath = Join-Path $LogDirectory "DatabaseRefresh_${TimeStamp}_${RunId}.log"

# SqlServer module v22+ defaults to Encrypt=Mandatory.
# Disabled bypasses SSL for internal SQL Servers with self-signed certificates.
$PSDefaultParameterValues['Invoke-Sqlcmd:Encrypt'] = 'Disabled'

#endregion Initialization

#region Logging

if (-not (Test-Path $LogDirectory)) {
    New-Item -Path $LogDirectory -ItemType Directory -Force | Out-Null
}

function Write-Log {
    param ([string]$Message, [string]$Level = 'INFO')
    $ts      = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $logLine = "$ts [$Level] $Message"
    Write-Output $logLine
    Add-Content -Path $LogFilePath -Value $logLine -ErrorAction SilentlyContinue
}

#endregion Logging

#region Validate Inputs

Write-Log "DatabaseRefresh starting. RunId: $RunId"
Write-Log "Script: $RestoreSqlScript | Instance: $SqlInstance"

if (-not (Test-Path $RestoreSqlScript)) {
    Write-Log "SQL script file not found: $RestoreSqlScript" 'ERROR'
    throw "SQL script file not found: $RestoreSqlScript. Ensure CreateRefreshScript.ps1 ran successfully."
}

$scriptContent = Get-Content $RestoreSqlScript -Raw
if ([string]::IsNullOrWhiteSpace($scriptContent)) {
    Write-Log "SQL script file is empty: $RestoreSqlScript" 'ERROR'
    throw "SQL script file is empty: $RestoreSqlScript"
}

Write-Log "Script file validated. Size: $((Get-Item $RestoreSqlScript).Length) bytes."

#endregion Validate Inputs

#region Execute Restore

$startTime = Get-Date

try {
    Write-Log "Executing restore script via Invoke-Sqlcmd..."

    Invoke-Sqlcmd `
        -ServerInstance  $SqlInstance `
        -InputFile       $RestoreSqlScript `
        -ConnectionTimeout 30 `
        -QueryTimeout    0 `
        -OutputSqlErrors $true `
        -TrustServerCertificate `
        -Verbose

    $duration = [math]::Round(((Get-Date) - $startTime).TotalMinutes, 1)
    Write-Log "Database restore completed successfully in ${duration} minutes."
}
catch {
    $duration = [math]::Round(((Get-Date) - $startTime).TotalMinutes, 1)
    Write-Log "Restore FAILED after ${duration} minutes." 'ERROR'
    Write-Log "Error: $($_.Exception.Message)" 'ERROR'
    Write-Log "Stack trace: $($_.Exception.StackTrace)" 'ERROR'
    throw
}
finally {
    $finTs = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Log "DatabaseRefresh execution finished at $finTs. RunId: $RunId"
}

#endregion Execute Restore
